{{- if .Values.externalSecret.enabled -}}
{{- $target := .Values.externalSecret.target | default dict -}}
{{- $data := (.Values.externalSecret.secrets | default .Values.externalSecret.data | default (list)) -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "donweather-front.fullname" . }}-ms-weather
  labels:
    {{- include "donweather-front.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name | quote }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind | quote }}
  target:
    name: {{ include "donweather-front.externalSecretTargetName" . | quote }}
    creationPolicy: {{ default "Owner" $target.creationPolicy | quote }}
  data:
    {{- toYaml $data | nindent 4 }}
{{- end }}

