replicaCount: 1

image:
  repository: buildbyte-container-registry.registry.twcstorage.ru/donweather-front
  pullPolicy: IfNotPresent
  tag: dev
  digest: "sha256:469b4d7dd25114df4b6a638563a89d448c2d200e623e6bc5013be9a8e2b0cda9"

imagePullSecrets:
  - name: registry-docker-registry
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

containerPort: 80

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

env: {}
envFrom: []

# Gateway API HTTPRoute (вместо Ingress).
httpRoute:
  enabled: true
  annotations: {}
  # parentRefs определяют к какому Gateway/Listener прикрепить маршрут.
  # Пример:
  # parentRefs:
  #   - name: my-gateway
  #     namespace: default
  #     sectionName: http
  # По умолчанию цепляемся к dev-gateway (HTTPS listener).
  parentRefs:
    - name: dev-gateway
      namespace: default
      sectionName: https-donweather
  hostnames:
    - donweather.dev.buildbyte.ru
  pathPrefix: /
  # Если нужно — можно передать полный массив spec.rules (как в Gateway API).
  rules: []

  # Redirect HTTP(80) -> HTTPS(443). Важно: укажите parentRefs на HTTP listener (например sectionName: http),
  # иначе при привязке к HTTPS listener получите redirect-loop.
  redirectToHttps:
    enabled: true
    annotations: {}
    # parentRefs для HTTP listener (обычно тот же Gateway, но sectionName=http)
    parentRefs:
      - name: dev-gateway
        namespace: default
        sectionName: http
    statusCode: 301
    scheme: https
    port: 443
